### ISSUE TITLE
Add Missing Photos and Animated GIFs to Wiki Pages

### ISSUE THREAD

**Issue by tiffhens** [ificouldseewhatyousee/ificouldsee#58]
example tools by themselves, individually
each material individually

**Comment by xianshun** [comment]
I am adding the recommended example images: https://github.com/ificouldseewhatyousee/ificouldsee/wiki/Instructions:-Teaching-a-Technique

**Comment by tiffhens** [comment]
I am adding images and gifs to this page:
[https://github.com/ificouldseewhatyousee/ificouldsee/wiki/Rural:-Building-your-own-Surveillance-Kit]

**Comment by tiffhens** [comment]
I am finishing adding images and gifs to this page.
https://github.com/ificouldseewhatyousee/ificouldsee/wiki/Rural:-Building-your-own-Surveillance-Kit

**Comment by tiffhens** [comment]
finished adding photos to the build-a-kit page.

**Comment by tiffhens** [comment]
finished adding photos to the materials and tools page.

**Comment by tiffhens** [comment]
pics appear to be done, closing task.
